#!/usr/bin/env bash
# Install nginx on server.

sudo apt-get update -y

sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'

sudo echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
