#!/usr/bin/env bash
# Install nginx on server.

apt-get update -y

apt-get install nginx -y
ufw allow 'Nginx HTTP'

service nginx restart

apt-get install curl -y

echo "Hello World!" > /var/www/html/index.html
