#!/usr/bin/env bash
# Install and configure HAproxy on this server.

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y

sudo systemctl enable haproxy

sudo sed -i '$a\\nfrontend webservers' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tbind *:80' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tmode http' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tdefault_backend servers' /etc/haproxy/haproxy.cfg

sudo sed -i '$a\\nbackend servers' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tbalance roundrobin' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tserver 530728-web-01 54.209.176.26:80 check' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tserver 530728-web-02 34.201.165.117:80 check' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
