#!/usr/bin/env bash
# Debug Nginx to run on port 80.

sudo apt update
sudo apt install nginx -y

CONFIG="
server {
	listen 0.0.0.0:80
}
"
sudo bash -c "echo \"$CONFIG\" >> /etc/nginx/nginx.conf"

sudo service nginx start
