#!/usr/bin/env bash
# Angry Bash script :)

# touch /var/run/myscript.pid
file=/var/run/myscript.pid
echo $$ > "$file"

trap 'echo I hate the kill command && rm -r "$file" && exit' SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap 'rm -r "$file" && exit' SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
