#!/usr/bin/env bash
# Bash script to display 'To infinity and beyond' indefinitely and traps SIGTERM.

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
