#!/usr/bin/env bash
# Bash script to implement the popular FizzBuzz from numbers 1 - 100.

for i in {1..100}
do
	if [ $(( i % 15 )) == 0 ]; then
		echo "FizzBuzz"
	elif [ $(( i % 3 )) == 0 ]; then
		echo "FizzBuzz"
	elif [ $(( i % 5 )) == 0 ]; then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
done
