#!/usr/bin/env bash
# Block all incoming traffic except 22, 443 and 80.

if ! type -P ufw; then
	sudo apt update
	sudo apt install ufw -y
fi

sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw reload
