#!/usr/bin/env bash
# Bash script to reconfigure and Ubuntu server.

cp /etc/hosts ~/hosts.new

sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '$a\8.8.8.8\t\tfacebook.com' ~/hosts.new

cp -f ~/hosts.new /etc/hosts
